services:
  web:
    build: ./webapp
    container_name: botbox_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: botbox_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:

#  llm:
#    image: ollama/llm:latest
#    container_name: botbox_llm
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./llm_models:/models

volumes:
  postgres_data: