services:
  web:
    build: ./webapp
    container_name: botbox_web
    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app
    env_file:
      - .env
    depends_on:
      - db
    # llm servisi olmadan çalışacak

  db:
    image: postgres:15
    container_name: botbox_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  llm:
#    image: ollama/llm:latest
#    container_name: botbox_llm
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./llm_models:/models

volumes:
  postgres_data: