# Generated by Django 4.2 on 2026-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='program_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tul',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='website',
            field=models.URLField(blank=True, default='https://www.acibadem.edu.tr'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='source',
            field=models.CharField(default='obs.acibadem.edu.tr', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='source',
            field=models.CharField(default='acibadem.edu.tr', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='universityinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
