# Generated by Django 4.2 on 2026-05-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=300)),
                ('faculty', models.CharField(blank=True, max_length=300)),
                ('expertise', models.TextField(blank=True)),
                ('profile_url', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(default='acibadem.edu.tr', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['faculty', 'department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
