# Generated by Django 4.2 on 2026-05-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_instructor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('name', 'faculty')},
        ),
    ]
