# Generated by Django 4.2 on 2026-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_instructor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='source',
            field=models.CharField(default='acibadem.edu.tr', max_length=300),
        ),
    ]
