apiVersion: v1
kind: ConfigMap
metadata:
  name: botbox-config
  namespace: default
data:
  OLLAMA_URL: "http://ollama:11434"
  OLLAMA_MODEL: "mistral"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "botboxdb"
  DEBUG: "False"
  AZURE_ENVIRONMENT: "AzurePublicCloud"
  PYTHONUNBUFFERED: "1"
