apiVersion: v1
kind: Secret
metadata:
  name: botbox-secrets
type: Opaque
stringData:
  POSTGRES_DB: botboxdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: sifre123
  SECRET_KEY: django-insecure-buraya-rastgele-bir-sey-yaz-123456789
  DATABASE_URL: postgresql://postgres:sifre123@db:5432/botboxdb