apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: botbox-web:v14 #<ACR_NAME>.azurecr.io/botbox-web:v8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: DEBUG
              value: "False"
            - name: DB_SSL
              value: "False"
            - name: POSTGRES_HOST
              value: db
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: botbox-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: botbox-secrets
                  key: DATABASE_URL
          command:
            - sh
            - -c
            - |
              until python -c "import socket; s=socket.create_connection(('db',5432),2)" 2>/dev/null; do
                echo "DB bekleniyor..."
                sleep 2
              done
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              python manage.py runserver 0.0.0.0:8000